CREATE TABLE agent_runs (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL,
    work_id BIGINT NOT NULL,
    chapter_id BIGINT NULL,
    ai_task_id BIGINT NULL,
    workflow_type VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    input_snapshot_version BIGINT NOT NULL,
    input_json JSON NOT NULL,
    input_hash CHAR(64) NOT NULL,
    run_status VARCHAR(32) NOT NULL,
    current_step_key VARCHAR(128) NULL,
    checkpoint_sequence BIGINT NOT NULL DEFAULT 0,
    timeout_at DATETIME NOT NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_agent_runs_user_workflow_idempotency (user_id, workflow_type, idempotency_key),
    UNIQUE KEY uk_agent_runs_ai_task_id (ai_task_id),
    KEY idx_agent_runs_status_timeout (run_status, timeout_at, id),
    KEY idx_agent_runs_chapter_gmt_create (chapter_id, gmt_create),
    CONSTRAINT fk_agent_runs_work_id FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_agent_runs_chapter_id FOREIGN KEY (chapter_id) REFERENCES chapters (id),
    CONSTRAINT fk_agent_runs_ai_task_id FOREIGN KEY (ai_task_id) REFERENCES ai_tasks (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_run_steps (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_id BIGINT NOT NULL,
    step_key VARCHAR(128) NOT NULL,
    attempt INT NOT NULL,
    step_status VARCHAR(32) NOT NULL,
    input_summary_json JSON NULL,
    output_summary_json JSON NULL,
    error_category VARCHAR(64) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    model_call_ref VARCHAR(128) NULL,
    retryable TINYINT NOT NULL DEFAULT 0,
    started_at DATETIME NULL,
    finished_at DATETIME NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_agent_run_steps_run_key_attempt (run_id, step_key, attempt),
    KEY idx_agent_run_steps_run_status (run_id, step_status, id),
    CONSTRAINT fk_agent_run_steps_run_id FOREIGN KEY (run_id) REFERENCES agent_runs (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_checkpoints (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_id BIGINT NOT NULL,
    step_id BIGINT NULL,
    sequence_id BIGINT NOT NULL,
    schema_version INT NOT NULL,
    step_key VARCHAR(128) NOT NULL,
    next_step_key VARCHAR(128) NULL,
    checkpoint_status VARCHAR(32) NOT NULL,
    state_json JSON NOT NULL,
    state_hash CHAR(64) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_agent_checkpoints_run_sequence (run_id, sequence_id),
    KEY idx_agent_checkpoints_run_latest (run_id, sequence_id DESC),
    CONSTRAINT fk_agent_checkpoints_run_id FOREIGN KEY (run_id) REFERENCES agent_runs (id),
    CONSTRAINT fk_agent_checkpoints_step_id FOREIGN KEY (step_id) REFERENCES agent_run_steps (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE agent_interruptions (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    run_id BIGINT NOT NULL,
    checkpoint_id BIGINT NOT NULL,
    step_id BIGINT NULL,
    interruption_type VARCHAR(32) NOT NULL,
    interruption_status VARCHAR(32) NOT NULL,
    resume_token_hash CHAR(64) NOT NULL,
    token_version INT NOT NULL,
    request_json JSON NOT NULL,
    response_json JSON NULL,
    response_hash CHAR(64) NULL,
    expires_at DATETIME NOT NULL,
    resumed_at DATETIME NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_agent_interruptions_run_status (run_id, interruption_status, id),
    CONSTRAINT fk_agent_interruptions_run_id FOREIGN KEY (run_id) REFERENCES agent_runs (id),
    CONSTRAINT fk_agent_interruptions_checkpoint_id FOREIGN KEY (checkpoint_id) REFERENCES agent_checkpoints (id),
    CONSTRAINT fk_agent_interruptions_step_id FOREIGN KEY (step_id) REFERENCES agent_run_steps (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
