CREATE TABLE IF NOT EXISTS works (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    biz_id VARCHAR(64) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'draft',
    current_chapter_id BIGINT NULL,
    chapter_count INT NOT NULL DEFAULT 0,
    word_count INT NOT NULL DEFAULT 0,
    last_opened_chapter_id BIGINT NULL,
    last_opened_at DATETIME NULL,
    created_by VARCHAR(64) NULL,
    updated_by VARCHAR(64) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_works_biz_id (biz_id),
    KEY idx_works_status_updated_at (status, updated_at),
    KEY idx_works_last_opened_at (last_opened_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS chapters (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    biz_id VARCHAR(64) NOT NULL,
    work_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    chapter_no INT NOT NULL,
    content LONGTEXT NULL,
    content_word_count INT NOT NULL DEFAULT 0,
    workflow_status VARCHAR(32) NOT NULL DEFAULT 'co_creation',
    last_workspace VARCHAR(32) NOT NULL DEFAULT 'co_creation',
    current_generation_id BIGINT NULL,
    current_brief_id BIGINT NULL,
    base_version INT NOT NULL DEFAULT 0,
    created_by VARCHAR(64) NULL,
    updated_by VARCHAR(64) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    last_opened_at DATETIME NULL,
    last_generated_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_chapters_biz_id (biz_id),
    UNIQUE KEY uk_chapters_work_id_chapter_no (work_id, chapter_no),
    KEY idx_chapters_workflow_status (work_id, workflow_status),
    KEY idx_chapters_last_opened_at (last_opened_at),
    CONSTRAINT fk_chapters_work_id FOREIGN KEY (work_id) REFERENCES works (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
