CREATE TABLE chapter_consensus_scope_candidates (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    work_id BIGINT NOT NULL,
    chapter_id BIGINT NULL,
    brief_id BIGINT NULL,
    task_id BIGINT NULL,
    scope VARCHAR(32) NOT NULL,
    target_ref_json JSON NULL,
    source_message_ids_json JSON NOT NULL,
    base_resource_type VARCHAR(64) NULL,
    base_version_id BIGINT NULL,
    base_version INT NULL,
    candidate_content_json JSON NOT NULL,
    confidence DECIMAL(5,4) NULL,
    candidate_status VARCHAR(32) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_consensus_scope_candidate_idempotency (idempotency_key),
    KEY idx_consensus_scope_candidate_work_status (work_id, candidate_status, id),
    KEY idx_consensus_scope_candidate_chapter_status (chapter_id, candidate_status, id),
    CONSTRAINT fk_consensus_scope_candidate_work FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_consensus_scope_candidate_chapter FOREIGN KEY (chapter_id) REFERENCES chapters (id),
    CONSTRAINT fk_consensus_scope_candidate_brief FOREIGN KEY (brief_id) REFERENCES chapter_briefs (id),
    CONSTRAINT fk_consensus_scope_candidate_task FOREIGN KEY (task_id) REFERENCES ai_tasks (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
