CREATE TABLE story_knowledge_extraction_batches (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    work_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    generation_id BIGINT NOT NULL,
    ai_task_id BIGINT NULL,
    agent_run_id BIGINT NULL,
    extractor_version VARCHAR(64) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    source_content_revision INT NOT NULL,
    source_fingerprint CHAR(64) NOT NULL,
    source_content LONGTEXT NOT NULL,
    batch_status VARCHAR(32) NOT NULL,
    candidate_count INT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_knowledge_extraction_generation_version (generation_id, extractor_version),
    UNIQUE KEY uk_knowledge_extraction_idempotency (idempotency_key),
    KEY idx_knowledge_extraction_chapter_status (chapter_id, batch_status, id),
    CONSTRAINT fk_knowledge_extraction_work FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_knowledge_extraction_chapter FOREIGN KEY (chapter_id) REFERENCES chapters (id),
    CONSTRAINT fk_knowledge_extraction_generation FOREIGN KEY (generation_id) REFERENCES chapter_generations (id),
    CONSTRAINT fk_knowledge_extraction_task FOREIGN KEY (ai_task_id) REFERENCES ai_tasks (id),
    CONSTRAINT fk_knowledge_extraction_run FOREIGN KEY (agent_run_id) REFERENCES agent_runs (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE story_knowledge_candidates (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    work_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    generation_id BIGINT NOT NULL,
    candidate_key VARCHAR(128) NOT NULL,
    candidate_type VARCHAR(32) NOT NULL,
    candidate_status VARCHAR(32) NOT NULL,
    payload_json JSON NOT NULL,
    evidence_start_offset INT NOT NULL,
    evidence_end_offset INT NOT NULL,
    evidence_text LONGTEXT NOT NULL,
    candidate_fingerprint CHAR(64) NOT NULL,
    conflict_target_id BIGINT NULL,
    confirmed_target_type VARCHAR(32) NULL,
    confirmed_target_id BIGINT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_story_knowledge_candidate_batch_key (batch_id, candidate_key),
    KEY idx_story_knowledge_candidate_batch_status (batch_id, candidate_status, id),
    KEY idx_story_knowledge_candidate_chapter_type (chapter_id, candidate_type, candidate_status),
    KEY idx_story_knowledge_candidate_fingerprint (work_id, candidate_type, candidate_fingerprint),
    CONSTRAINT fk_story_knowledge_candidate_batch FOREIGN KEY (batch_id)
        REFERENCES story_knowledge_extraction_batches (id),
    CONSTRAINT fk_story_knowledge_candidate_work FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_story_knowledge_candidate_chapter FOREIGN KEY (chapter_id) REFERENCES chapters (id),
    CONSTRAINT fk_story_knowledge_candidate_generation FOREIGN KEY (generation_id) REFERENCES chapter_generations (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
