CREATE TABLE chapter_capacity_assessments (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    work_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    chapter_plan_version_id BIGINT NOT NULL,
    scene_plan_no INT NOT NULL,
    target_word_count INT NOT NULL,
    length_preset VARCHAR(32) NOT NULL,
    custom_word_count INT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    input_fingerprint CHAR(64) NOT NULL,
    brief_template_version VARCHAR(64) NOT NULL,
    brief_fingerprint CHAR(64) NOT NULL,
    source_snapshot_json JSON NOT NULL,
    assessment_status VARCHAR(32) NOT NULL,
    result_json JSON NULL,
    evaluator_version VARCHAR(64) NOT NULL,
    ai_task_id BIGINT NULL,
    agent_run_id BIGINT NULL,
    model_call_id BIGINT NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(512) NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_capacity_assessment_idempotency (chapter_id, idempotency_key),
    KEY idx_capacity_assessment_plan (chapter_plan_version_id, assessment_status, id),
    CONSTRAINT fk_capacity_assessment_work FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_capacity_assessment_chapter FOREIGN KEY (chapter_id) REFERENCES chapters (id),
    CONSTRAINT fk_capacity_assessment_plan FOREIGN KEY (chapter_plan_version_id) REFERENCES chapter_plan_versions (id),
    CONSTRAINT fk_capacity_assessment_task FOREIGN KEY (ai_task_id) REFERENCES ai_tasks (id),
    CONSTRAINT fk_capacity_assessment_run FOREIGN KEY (agent_run_id) REFERENCES agent_runs (id),
    CONSTRAINT fk_capacity_assessment_model_call FOREIGN KEY (model_call_id) REFERENCES llm_model_calls (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
