CREATE TABLE chapter_selection_assistance (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    work_id BIGINT NOT NULL,
    chapter_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    ai_task_id BIGINT NULL,
    agent_run_id BIGINT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    operation_type VARCHAR(32) NOT NULL,
    request_status VARCHAR(32) NOT NULL,
    base_chapter_version INT NOT NULL,
    base_content_hash CHAR(64) NOT NULL,
    selection_start INT NOT NULL,
    selection_end INT NOT NULL,
    selected_text LONGTEXT NOT NULL,
    adjacent_before TEXT NULL,
    adjacent_after TEXT NULL,
    user_instruction TEXT NULL,
    brief_template_version VARCHAR(64) NOT NULL,
    brief_fingerprint CHAR(64) NOT NULL,
    brief_content MEDIUMTEXT NOT NULL,
    input_fingerprint CHAR(64) NOT NULL,
    result_content LONGTEXT NULL,
    diff_json JSON NULL,
    fact_risk_status VARCHAR(32) NULL,
    fact_risk_reasons_json JSON NULL,
    model_call_ref VARCHAR(128) NULL,
    error_code VARCHAR(64) NULL,
    error_message VARCHAR(500) NULL,
    accepted_chapter_version INT NULL,
    deleted TINYINT NOT NULL DEFAULT 0,
    version INT NOT NULL DEFAULT 0,
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_selection_assistance_idempotency (chapter_id, idempotency_key),
    KEY idx_selection_assistance_chapter_status (chapter_id, request_status, id),
    KEY idx_selection_assistance_parent (parent_id, id),
    CONSTRAINT fk_selection_assistance_work FOREIGN KEY (work_id) REFERENCES works (id),
    CONSTRAINT fk_selection_assistance_chapter FOREIGN KEY (chapter_id) REFERENCES chapters (id),
    CONSTRAINT fk_selection_assistance_parent FOREIGN KEY (parent_id) REFERENCES chapter_selection_assistance (id),
    CONSTRAINT fk_selection_assistance_task FOREIGN KEY (ai_task_id) REFERENCES ai_tasks (id),
    CONSTRAINT fk_selection_assistance_run FOREIGN KEY (agent_run_id) REFERENCES agent_runs (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
