CREATE TABLE chapter_prose_candidate_adoptions (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '采纳记录 ID',
    work_id BIGINT NOT NULL COMMENT '作品 ID',
    chapter_id BIGINT NOT NULL COMMENT '章节 ID',
    candidate_id BIGINT NOT NULL COMMENT '正文候选 ID',
    candidate_version INT NOT NULL COMMENT '冻结候选版本',
    candidate_content_hash CHAR(64) NOT NULL COMMENT '冻结候选正文哈希',
    expected_formal_version INT NOT NULL COMMENT '作者确认的正式正文版本',
    quality_report_id BIGINT NOT NULL COMMENT '精确整章质量报告 ID',
    idempotency_key VARCHAR(128) NOT NULL COMMENT '作者采纳幂等键',
    adoption_mode VARCHAR(32) NOT NULL COMMENT 'direct_formal 或 revision_release',
    adoption_status VARCHAR(32) NOT NULL COMMENT 'completed、impact_pending 或 impact_running',
    formal_result_version INT NULL COMMENT '未发布章节采纳后的正文版本',
    formal_result_hash CHAR(64) NULL COMMENT '未发布章节采纳后的正文哈希',
    revision_id BIGINT NULL COMMENT '已发布章节创建或复用的不可变 revision',
    workspace_id BIGINT NULL COMMENT '活动 revision workspace',
    impact_report_id BIGINT NULL COMMENT '幂等影响分析报告',
    error_code VARCHAR(64) NULL COMMENT '安全恢复错误码',
    deleted TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除',
    version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本',
    gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
    PRIMARY KEY (id),
    UNIQUE KEY uk_prose_adoption_chapter_key (chapter_id, idempotency_key),
    UNIQUE KEY uk_prose_adoption_candidate_version (candidate_id, candidate_version),
    KEY idx_prose_adoption_recovery (adoption_status, id),
    KEY idx_prose_adoption_workspace (workspace_id, revision_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='正文候选唯一采纳记录';
