ALTER TABLE works COMMENT = '作品表';
ALTER TABLE works
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN biz_id VARCHAR(64) NOT NULL COMMENT '业务唯一ID',
    MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '作品标题',
    MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT '作品状态',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    MODIFY COLUMN gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE chapters COMMENT = '章节表';
ALTER TABLE chapters
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN biz_id VARCHAR(64) NOT NULL COMMENT '业务唯一ID',
    MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '所属作品ID',
    MODIFY COLUMN title VARCHAR(255) NOT NULL COMMENT '章节标题',
    MODIFY COLUMN chapter_no INT NOT NULL COMMENT '章节序号',
    MODIFY COLUMN content LONGTEXT NULL COMMENT '章节正文，章节内容唯一事实源',
    MODIFY COLUMN workflow_status VARCHAR(32) NOT NULL DEFAULT 'co_creation' COMMENT '章节工作流状态',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号，当前用于正文版本控制',
    MODIFY COLUMN gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE chapter_conversations COMMENT = '章节会话表';
ALTER TABLE chapter_conversations
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN biz_id VARCHAR(64) NOT NULL COMMENT '业务唯一ID',
    MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '所属作品ID',
    MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '所属章节ID',
    MODIFY COLUMN conversation_type VARCHAR(32) NOT NULL DEFAULT 'chapter_co_creation' COMMENT '会话类型：chapter_co_creation章节共创，chapter_editing章节编辑',
    MODIFY COLUMN conversation_status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '会话状态',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    MODIFY COLUMN gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE chapter_conversation_messages COMMENT = '章节会话消息表';
ALTER TABLE chapter_conversation_messages
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN biz_id VARCHAR(64) NOT NULL COMMENT '业务唯一ID',
    MODIFY COLUMN conversation_id BIGINT NOT NULL COMMENT '所属会话ID',
    MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '所属章节ID',
    MODIFY COLUMN message_role VARCHAR(32) NOT NULL COMMENT '消息角色：user用户，assistant助手，system系统',
    MODIFY COLUMN content LONGTEXT NOT NULL COMMENT '消息正文',
    MODIFY COLUMN ai_task_id BIGINT NULL COMMENT '关联AI任务ID',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    MODIFY COLUMN gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE chapter_briefs COMMENT = '章节共创收束摘要表';
ALTER TABLE chapter_briefs
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN biz_id VARCHAR(64) NOT NULL COMMENT '业务唯一ID',
    MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '所属作品ID',
    MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '所属章节ID',
    MODIFY COLUMN brief_status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT '摘要状态',
    MODIFY COLUMN brief_content LONGTEXT NOT NULL COMMENT 'AI或会话收束出的摘要、候选结构卡或中间结果',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    MODIFY COLUMN gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE chapter_generations COMMENT = '章节正文生成记录表';
ALTER TABLE chapter_generations
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN biz_id VARCHAR(64) NOT NULL COMMENT '业务唯一ID',
    MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '所属作品ID',
    MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '所属章节ID',
    MODIFY COLUMN brief_id BIGINT NULL COMMENT '关联章节收束摘要ID',
    MODIFY COLUMN outline_id BIGINT NULL COMMENT '生成依据的正式章节大纲ID',
    MODIFY COLUMN outline_revision INT NULL COMMENT '生成依据的大纲修订版本',
    MODIFY COLUMN generation_status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT '生成状态',
    MODIFY COLUMN generation_mode VARCHAR(32) NULL COMMENT '生成模式',
    MODIFY COLUMN length_preset VARCHAR(32) NULL COMMENT '字数预设',
    MODIFY COLUMN custom_word_count INT NULL COMMENT '自定义目标字数',
    MODIFY COLUMN basis_snapshot_json JSON NULL COMMENT '生成依据快照JSON',
    MODIFY COLUMN generated_content LONGTEXT NULL COMMENT '生成正文内容',
    MODIFY COLUMN word_count INT NOT NULL DEFAULT 0 COMMENT '生成正文字数',
    MODIFY COLUMN ai_task_id BIGINT NULL COMMENT '关联AI任务ID',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    MODIFY COLUMN gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE chapter_outlines COMMENT = '章节大纲表';
ALTER TABLE chapter_outlines
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN biz_id VARCHAR(64) NOT NULL COMMENT '业务唯一ID',
    MODIFY COLUMN work_id BIGINT NOT NULL COMMENT '所属作品ID',
    MODIFY COLUMN chapter_id BIGINT NOT NULL COMMENT '所属章节ID',
    MODIFY COLUMN outline_status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT '大纲状态：draft草稿，confirmed已确认，outdated已过期',
    MODIFY COLUMN outline_content JSON NOT NULL COMMENT '大纲内容JSON，包含本章目标、场景列表、人物变化、情绪节奏、生成约束和未决问题',
    MODIFY COLUMN revision INT NOT NULL DEFAULT 0 COMMENT '大纲修订版本号，用于乐观锁',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
    MODIFY COLUMN gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE user_configs COMMENT = '用户配置表';
ALTER TABLE user_configs
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN biz_id VARCHAR(64) NOT NULL COMMENT '业务唯一ID',
    MODIFY COLUMN user_id VARCHAR(64) NOT NULL COMMENT '用户ID',
    MODIFY COLUMN config_key VARCHAR(128) NOT NULL COMMENT '配置键，如model.active、writing.preferences、appearance.preferences',
    MODIFY COLUMN config_value JSON NOT NULL COMMENT '配置值JSON',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    MODIFY COLUMN gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE ai_tasks COMMENT = 'AI异步任务表';
ALTER TABLE ai_tasks
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN biz_id VARCHAR(64) NOT NULL COMMENT '业务唯一ID',
    MODIFY COLUMN task_type VARCHAR(32) NOT NULL COMMENT '任务类型',
    MODIFY COLUMN task_status VARCHAR(32) NOT NULL DEFAULT 'queued' COMMENT '任务状态：queued排队中，running运行中，succeeded成功，failed失败，canceled已取消',
    MODIFY COLUMN work_id BIGINT NULL COMMENT '关联作品ID',
    MODIFY COLUMN chapter_id BIGINT NULL COMMENT '关联章节ID',
    MODIFY COLUMN result_message_id BIGINT NULL COMMENT '成功后生成的消息ID',
    MODIFY COLUMN result_generation_id BIGINT NULL COMMENT '成功后生成的正文生成记录ID',
    MODIFY COLUMN result_suggestion_id BIGINT NULL COMMENT '成功后生成的编辑建议ID',
    MODIFY COLUMN error_code VARCHAR(64) NULL COMMENT '失败错误码',
    MODIFY COLUMN error_message VARCHAR(500) NULL COMMENT '失败错误信息',
    MODIFY COLUMN deleted TINYINT NOT NULL DEFAULT 0 COMMENT '是否删除：0否，1是',
    MODIFY COLUMN version INT NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    MODIFY COLUMN gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN gmt_modified DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
